apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: 2018-12-02T15:22:12Z
  labels:
    run: sudo-fish
  name: sudo-fish
  namespace: ingress-controller
  selfLink: /apis/extensions/v1beta1/namespaces/ingress-controller/deployments/sudo-fish
  uid: 0ae0a1fd-f646-11e8-9d12-002590c73e0c
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: sudo-fish
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: sudo-fish
    spec:
      containers:
      - image: registry.tr0:5000/sudofish:1.4
        imagePullPolicy: IfNotPresent
        name: sudo-fish
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: 2018-12-02T15:22:16Z
    lastUpdateTime: 2018-12-02T15:22:16Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-12-02T15:22:12Z
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
